[Data]
adj_filename = /home/user/FSTLLM/contrast/Traffic-Benchmark-master/methods/ASTGCN/data/subway/distance.csv
graph_signal_matrix_filename = /home/user/FSTLLM/contrast/Traffic-Benchmark-master/methods/ASTGCN/data/subway/
num_of_vertices = 34
points_per_hour = 8
num_for_predict = 8
len_input = 8
dataset_name = subway

[Training]
ctx = 0
in_channels = 1
nb_block = 2
K = 3
nb_chev_filter = 64
nb_time_filter = 64
batch_size = 32
model_name = astgcn_r
dataset_name = subway
num_of_weeks = 0
num_of_days = 0
num_of_hours = 1
start_epoch = 0
epochs = 100
learning_rate = 0.001
